spring.application.name=api-gestion-espacios

# Configuracion de la conexion a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/api_test
spring.datasource.username=root
spring.datasource.password=nico2891

# Driver JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true

# Clave secreta para JWT
jwt.secret="clave-super-secreta-para-firmar-los-jwt-segura-y-larga"

logging.level.org.springframework.security=DEBUG